"""catalog.py -- the monsters we want, as intent rather than artifacts.

This file is tracked.  It says *what* to make and with which parameters; it
never holds a task id, a result URL or an API key.  Those are artifacts of a
particular run and live in assets/cache/meshy/<id>/task.json, which is
git-ignored -- the same split ``asset_sources.py`` draws between the thing
described and the thing restored.

── Two parameters carry most of the outcome ────────────────────────────────

``pose_mode`` is "a-pose" for every humanoid, always.  SK_Mannequin -- the
skeleton ABP_Unarmed drives -- is authored in A-pose, and a source mesh
generated in T-pose retargets onto it with the shoulders wrong.  The API
parameter is authoritative, so the prompt text must not argue with it: the
zombie description as first written asked for a T-pose and has been
normalised to match.

``enable_pbr`` (set in providers/meshy.py, not here) defaults to FALSE at the
API.  Without it a refine returns base colour only -- no normal, roughness or
metallic -- which reads as flat plastic.  Every realism claim in these prompts
depends on it being on.

Textures are generated at 4k because that is the cheap direction to be wrong
in: Unreal can clamp a 4k source down at import with a max-texture-size or LOD
bias, but it cannot invent detail that was never generated.  Ship-time value
is likely 2k; generation-time value is 4k.
"""

from dataclasses import dataclass

# Measured from SKM_Quinn_Simple on 2026-09-27: box_extent.z 90.084 * 2 =
# 180.17 uu = 1.802 m.  The zombie matches it so that retargeted locomotion
# needs no scale compensation at all.
QUINN_HEIGHT_M = 1.80


@dataclass(frozen=True)
class MonsterSpec:
    """One character: what to generate, how big, and where it lands.

    The name is historical -- the player's adventurer is described by one of
    these too.  Nothing in the shape of a generation request distinguishes a
    monster from a protagonist; what makes the adventurer the player is that
    ``build_weapons_and_combat.py`` wears it and ``npc_placement.NPC_VARIANTS``
    does not list it.
    """

    id: str
    prompt: str
    height_meters: float
    dest: str
    target_polycount: int = 30000
    texture_resolution: str = "4k"
    pose_mode: str = "a-pose"
    ai_model: str = "meshy-7.1"
    provider: str = "meshy"
    license: str = "meshy-commercial"
    note: str = ""


MONSTERS = (
    MonsterSpec(
        id="zombie_01",
        prompt=(
            "Realistic horror game zombie, modern era humanoid male, decaying "
            "flesh, torn and bloody hospital gown, exposed bone visible on the "
            "jawline and ribcage, pallid grey mottled skin, sunken glowing "
            "eyes, A-pose, highly detailed, PBR textures, dark survival horror "
            "aesthetic, Unreal Engine 5 style, photorealistic, 4k resolution, "
            "symmetrical posture for rigging"
        ),
        height_meters=QUINN_HEIGHT_M,
        dest="/Game/Sourced/Characters/SKM_Zombie01",
        note="The easy case: human proportions, human silhouette. If the "
             "shared-skeleton idea fails here it fails everywhere.",
    ),
    MonsterSpec(
        id="wendigo_01",
        prompt=(
            "Realistic horror game wendigo, terrifying humanoid creature with "
            "abnormally prolonged emaciated arms, rotting deer skull for a head "
            "with large jagged antlers, tight leathery grey skin stretched "
            "tightly over visible ribs and spine, elongated sharp bone-like "
            "claws on hands, A-pose, highly detailed, PBR textures, dark "
            "fantasy horror, Unreal Engine 5 style, photorealistic, 4k "
            "resolution, symmetrical posture for rigging"
        ),
        height_meters=2.40,
        dest="/Game/Sourced/Characters/SKM_Wendigo01",
        note="The stress test. Antlers are not limbs and the arms are "
             "deliberately out of human proportion, both of which push at what "
             "Meshy's pose estimation says it supports. A failure here is a "
             "result, not a waste: it marks the boundary of the humanoid path.",
    ),
)


# ── The player ───────────────────────────────────────────────────────────────
#
# Generated by exactly the same four stages as the monsters, and deliberately
# at QUINN_HEIGHT_M: the retargeter takes the mannequin's locomotion onto this
# rig, and matching the source's height is what keeps the stride length honest
# without a scale correction.
#
# Two things the prompt does NOT ask for, both for reasons of where the camera
# is.  No backpack: the boom sits 260 cm behind and 55 cm right of the player
# (CAMERA_SHOULDER in combat/camera.py), so anything on the upper
# back is drawn across the middle of the screen at all times.  And no long
# coat or cloak: Meshy skins loose geometry to the nearest bone, so a hem hangs
# off the thighs and scissors open on every stride.
ADVENTURER = MonsterSpec(
    id="adventurer_01",
    prompt=(
        "Realistic survival horror game protagonist, modern era human male "
        "monster hunter, weathered rugged face with short stubble and cropped "
        "dark hair, worn waxed canvas field jacket with the sleeves pushed up "
        "over a dark hooded base layer, low-profile chest rig with pouches and "
        "straps, reinforced work trousers tucked into scuffed leather boots, "
        "fingerless gloves, mud-stained and blood-flecked practical gear, no "
        "backpack, A-pose, highly detailed, PBR textures, dark survival horror "
        "aesthetic, Unreal Engine 5 style, photorealistic, 4k resolution, "
        "symmetrical posture for rigging"
    ),
    height_meters=QUINN_HEIGHT_M,
    dest="/Game/Sourced/Characters/SKM_Adventurer01",
    note="The player. Ordinary human proportions on purpose -- this is the "
         "easiest thing Meshy's pose estimation can be asked for, and the "
         "player is the one character a bad rig cannot be hidden on.",
)

# ── The player's base body, for clothing ─────────────────────────────────────
#
# The same man as ADVENTURER, stripped to a pair of boxers: the body the
# clothing system dresses (Scripts/clothing/CLAUDE.md). Garments are drawn over
# it one slot at a time, so the base must carry nothing a slot would add -- no
# shirt, no gloves, no boots, no hat -- and the boxers are what it wears with
# every slot empty. Bare skin is also the easy case for Meshy's rigger: no
# loose hem or cuff for it to skin to the wrong bone.
#
# Not worn yet. The player still wears ADVENTURER (combat/skin.py) until the
# clothing task moves the player onto this rig; until then it is imported on
# its own skeleton and left alone.
ADVENTURER_BASE = MonsterSpec(
    id="adventurer_02",
    # Led by what he wears, and with nothing about horror or survival: the
    # first try, worded as a "survival horror protagonist ... wearing only
    # boxer shorts", came back in camo cargo trousers and combat boots.
    prompt=(
        "Full body 3D character, an adult man wearing nothing but plain dark "
        "grey cotton boxer shorts underwear, barefoot with bare toes, bare "
        "knees and bare legs, shirtless with a bare chest, lean athletic "
        "build, weathered rugged face with short stubble and cropped dark "
        "hair, base mesh for a clothing system, A-pose with the arms angled "
        "down and away from the body, hands open with fingers apart, "
        "photorealistic skin, PBR textures, Unreal Engine 5 style, 4k "
        "resolution, symmetrical posture for rigging"
    ),
    height_meters=QUINN_HEIGHT_M,
    dest="/Game/Sourced/Characters/SKM_Adventurer02",
    note="The player in boxers, the base the garments go on. The same face "
         "and height as adventurer_01, so moving the player onto it changes "
         "the clothes and nothing else.",
)

# What fetch_monsters.py iterates. MONSTERS is kept as its own name because
# npc_placement.py's variants and the spawn logic are about monsters only.
CHARACTERS = MONSTERS + (ADVENTURER, ADVENTURER_BASE)


def by_id(spec_id: str):
    for spec in CHARACTERS:
        if spec.id == spec_id:
            return spec
    raise KeyError(f"no character spec with id {spec_id!r}")
