#!/usr/bin/env python3
"""swap_player_body.py -- put the player in another generated body. Host-side.

    python3 Scripts/asset_pipeline/swap_player_body.py adventurer_03
    python3 Scripts/asset_pipeline/swap_player_body.py --plan adventurer_03   # print only
    python3 Scripts/asset_pipeline/swap_player_body.py --check               # verifiers only

It is the one setting (player_body.PLAYER_BODY) and the builds that follow
from it, in the order they must run:

    1. the setting is written into asset_pipeline/player_body.py
    2. Content/Weapons/Anims is emptied: the weapons build keys those pose
       clips on the worn skeleton, and one left on another body's has to be
       deleted through the editor first, which takes minutes apiece
    3. in ONE fresh editor (each boot is 25 seconds):
         import_body.py            only if the body has never been imported
         retarget_player_clips.py  the stance, kneel and throw clips, on that
                                   body (not import_quaternius.py, which also
                                   re-imports every pack: six minutes)
         the weapons, survival, menu and clothing builds (the weapons build
         poses every weapon in the worn body's hands)
    4. build_item_icons.py Character   the I panel's portrait, a picture of
       the body the built character now wears
    5. the verifiers, in a fresh editor

About five minutes.

Close the editor first: every step runs cold, and a cold build under an open
editor is overwritten by it (CLAUDE.md, "Never cold-run a builder").
"""

import argparse
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SCRIPTS = os.path.dirname(HERE)
sys.path.insert(0, SCRIPTS)

from asset_pipeline import catalog                      # noqa: E402

SETTING = os.path.join(HERE, "player_body.py")
UEPY = os.path.join(SCRIPTS, "dev", "uepy.py")
# One editor: the import (if any), the clips, then the builds.
BUILDS = ("asset_pipeline/import_body.py",
          "asset_pipeline/retarget_player_clips.py",
          "build_weapons_and_combat.py", "build_survival.py",
          "build_graphics_menu.py", "build_clothing.py")
# Run as it is, not through uepy.py: it drives the editor itself.
PORTRAIT = ("build_item_icons.py", "Character")
VERIFIERS = ("verify_weapons_and_combat.py", "verify_survival.py",
             "verify_graphics_menu.py", "verify_clothing.py",
             "verify_npc_blueprints.py")
POSE_CLIPS = os.path.join(os.path.dirname(SCRIPTS), "Content", "Weapons", "Anims")
_LINE = re.compile(r'^PLAYER_BODY = "([^"]*)"$', re.M)


def current():
    with open(SETTING) as fh:
        return _LINE.search(fh.read()).group(1)


def write_setting(spec_id):
    with open(SETTING) as fh:
        text = fh.read()
    new, n = _LINE.subn(f'PLAYER_BODY = "{spec_id}"', text)
    if n != 1:
        raise RuntimeError(f"{SETTING}: expected one PLAYER_BODY line, found {n}")
    with open(SETTING, "w") as fh:
        fh.write(new)


def steps(check_only=False):
    """[(what, [scripts])] in order; each list is one cold editor."""
    verify = ("the verifiers", VERIFIERS)
    if check_only:
        return [verify]
    return [("the import (if needed), the clips and the builds", BUILDS),
            ("the I panel's portrait", PORTRAIT), verify]


def clear_pose_clips():
    """Remove the pose clips the weapons build keys (all generated by it)."""
    gone = 0
    if os.path.isdir(POSE_CLIPS):
        for name in os.listdir(POSE_CLIPS):
            if name.endswith(".uasset"):
                os.remove(os.path.join(POSE_CLIPS, name))
                gone += 1
    return gone


def command(scripts):
    if scripts is PORTRAIT:
        return [sys.executable, os.path.join(SCRIPTS, PORTRAIT[0]), *PORTRAIT[1:]]
    return [sys.executable, UEPY, "--cold", "--summary",
            *(os.path.join(SCRIPTS, s) for s in scripts)]


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("id", nargs="?", help="catalog id of the body to wear")
    ap.add_argument("--plan", action="store_true", help="print the steps, run nothing")
    ap.add_argument("--check", action="store_true", help="run the verifiers only")
    args = ap.parse_args(argv)

    target = args.id or current()
    catalog.by_id(target)                     # a KeyError names a bad id
    todo = steps(check_only=args.check)
    if args.plan:
        print(f"player body: {current()} -> {target}")
        if target != current():
            print(f'  edit {os.path.relpath(SETTING)}: PLAYER_BODY = "{target}"')
        for what, scripts in todo:
            if scripts is BUILDS:
                print(f"  rm {os.path.relpath(POSE_CLIPS)}/*.uasset")
            print(f"  # {what}\n  " + " ".join(
                os.path.relpath(a) if os.sep in a else a for a in command(scripts)[1:]))
        return 0

    if not args.check and target != current():
        write_setting(target)
        print(f"[swap] PLAYER_BODY = {target}", flush=True)
    failed = 0
    for what, scripts in todo:
        print(f"[swap] {what}", flush=True)
        if scripts is BUILDS:
            print(f"[swap] cleared {clear_pose_clips()} pose clip(s) for the "
                  "build to key afresh", flush=True)
        code = subprocess.call(command(scripts))
        if code and scripts is not VERIFIERS:
            print(f"[swap] stopped: {what} failed (exit {code})")
            return code
        failed = failed or code
    print(f"[swap] the player is {target}"
          + (" -- with failed checks, above" if failed else ", every check passed"))
    return failed


if __name__ == "__main__":
    sys.exit(main())
