"""
Auto-generated Unreal import script for Lvl_Probe_50m.
Generated by generate_forest_level.py
World size: 50.0m × 50.0m
Time of day: Night — starry sky as the only light source, low luminosity
Tree density: x2 (18 trees)
"""
import json
import os
import sys
import unreal

asset_tools = unreal.AssetToolsHelpers.get_asset_tools()
editor_asset_sub = unreal.get_editor_subsystem(unreal.EditorAssetSubsystem)
editor_actor_sub = unreal.get_editor_subsystem(unreal.EditorActorSubsystem)
level_editor_sub = unreal.get_editor_subsystem(unreal.LevelEditorSubsystem)
mel = unreal.MaterialEditingLibrary

LEVEL_NAME = "Lvl_Probe_50m"
WORLD_SIZE_CM = 5000.0
OBJ_PATH = r"/Users/alexeysukhov/Documents/Unreal Projects/Otherworld/Scripts/generated_levels/Lvl_Probe_50m/SM_Lvl_Probe_50m_Terrain.obj"
MESH_ASSET_NAME = "SM_Lvl_Probe_50m_Terrain"
MESH_CONTENT_PATH = "/Game/Forest/Test/" + MESH_ASSET_NAME

unreal.log_warning("=" * 60)
unreal.log_warning(f"[GEN] Importing {LEVEL_NAME} ({WORLD_SIZE_CM / 100.0}m x {WORLD_SIZE_CM / 100.0}m)")
unreal.log_warning("=" * 60)

# ── 1. Import OBJ terrain mesh ───────────────────────────────────────
unreal.log_warning("[GEN] 1. Importing terrain mesh...")
task = unreal.AssetImportTask()
task.filename = OBJ_PATH
task.destination_path = "/Game/Forest/Test"
task.destination_name = MESH_ASSET_NAME
task.replace_existing = True
task.automated = True
task.save = True
asset_tools.import_asset_tasks([task])

terrain_mesh = editor_asset_sub.load_asset(
    MESH_CONTENT_PATH + "." + MESH_ASSET_NAME
)
if not terrain_mesh:
    unreal.log_error(f"[GEN] FAILED to import terrain mesh from {OBJ_PATH}")
else:
    # Disable Nanite, enable complex collision
    nanite = terrain_mesh.get_editor_property("nanite_settings")
    if nanite:
        nanite.set_editor_property("enabled", False)
        terrain_mesh.set_editor_property("nanite_settings", nanite)

    body_setup = terrain_mesh.get_editor_property("body_setup")
    if body_setup:
        body_setup.set_editor_property(
            "collision_trace_flag",
            unreal.CollisionTraceFlag.CTF_USE_COMPLEX_AS_SIMPLE
        )

    terrain_mesh.set_editor_property("allow_cpu_access", True)

    # Assign ground material
    ground_mat = editor_asset_sub.load_asset(
        "/Game/Forest/Materials/M_Forest_Ground_PBR.M_Forest_Ground_PBR"
    )
    if ground_mat:
        terrain_mesh.set_material(0, ground_mat)

    editor_asset_sub.save_loaded_asset(terrain_mesh)
    unreal.log_warning("[GEN] Terrain mesh imported with complex collision enabled!")

# ── 2. Create / load the level ───────────────────────────────────────
unreal.log_warning("[GEN] 2. Creating level...")
map_path = f"/Game/Maps/{LEVEL_NAME}"

if editor_asset_sub.does_asset_exist(map_path):
    level_editor_sub.load_level(map_path)
    # Remove existing generated actors to allow clean re-generation
    for a in editor_actor_sub.get_all_level_actors():
        lbl = a.get_actor_label()
        if (lbl.startswith(LEVEL_NAME)
                or lbl.startswith("HISM_Tree")
                or lbl.startswith("HISM_Grass")
                or lbl.startswith("HISM_Bush")):
            editor_actor_sub.destroy_actor(a)
else:
    level_editor_sub.new_level(map_path)

# ── 3. Spawn terrain actor ───────────────────────────────────────────
unreal.log_warning("[GEN] 3. Spawning terrain actor...")
terrain_actor = editor_actor_sub.spawn_actor_from_class(
    unreal.StaticMeshActor,
    unreal.Vector(0, 0, 0),
    unreal.Rotator(0, 0, 0),
)
terrain_actor.set_actor_label(f"{LEVEL_NAME}_Terrain")
smc = terrain_actor.get_component_by_class(unreal.StaticMeshComponent)
if smc:
    smc.set_static_mesh(terrain_mesh)
    smc.set_collision_profile_name("BlockAll")
    smc.set_collision_enabled(unreal.CollisionEnabled.QUERY_AND_PHYSICS)
    smc.set_mobility(unreal.ComponentMobility.STATIC)

# ── 4. Spawn lighting & sky (Night — starry sky as the only light source, low luminosity) ─────────────────────────────
unreal.log_warning("[GEN] 4. Setting up lighting and sky — Night — starry sky as the only light source, low luminosity")

LIGHTING = json.loads(r"""{"key": "night", "label": "Night \u2014 starry sky as the only light source, low luminosity", "sun": {"enabled": true, "label_suffix": "Moon", "intensity": 0.12, "color": [170, 195, 255], "pitch": -32.0, "yaw": 120.0, "cast_shadows": true, "shadow_distance_cm": 10000.0}, "sky_light": {"intensity": 3.0, "real_time_capture": true}, "sky_dome": {"enabled": true, "material": "/Game/Forest/Materials/M_NightSky_Starfield", "build_starfield": true, "star_brightness": 2.5, "night_sky_color": [0.004, 0.008, 0.022, 1.0], "star_tiling": [2.0, 1.0]}, "volumetric_cloud": {"enabled": false}, "fog": {"density": 0.035, "inscattering_color": [0.015, 0.025, 0.055], "enable_volumetric": true, "volumetric_extinction_scale": 0.6}, "post_process": {"auto_exposure_min_brightness": 0.004, "auto_exposure_max_brightness": 0.6, "auto_exposure_bias": 1.6}}""")

def srgb(c):
    return unreal.Color(r=c[0], g=c[1], b=c[2], a=255)

def linear(c):
    return unreal.LinearColor(c[0], c[1], c[2], c[3] if len(c) > 3 else 1.0)

def try_set(obj, prop, value, quiet=False):
    """Set an editor property, logging (not raising) if it is unavailable."""
    try:
        obj.set_editor_property(prop, value)
        return True
    except Exception as exc:
        if not quiet:
            unreal.log_warning(f"[GEN]   (skipped {prop}: {exc})")
        return False

def try_set_first(obj, props, value):
    """Set the first property name that exists (engine versions differ)."""
    for i, prop in enumerate(props):
        if try_set(obj, prop, value, quiet=(i < len(props) - 1)):
            return True
    return False

def ensure_starfield_material(cfg):
    """Build the unlit emissive starfield sky-dome material + instance."""
    base_path = cfg["material"]
    base_name = base_path.rsplit("/", 1)[-1]
    base_pkg = base_path.rsplit("/", 1)[0]
    base = editor_asset_sub.load_asset(base_path + "." + base_name)

    if not base:
        unreal.log_warning(f"[GEN]   Creating {base_path}")
        base = asset_tools.create_asset(
            base_name, base_pkg, unreal.Material, unreal.MaterialFactoryNew()
        )
        # Unlit + two-sided + IsSky so height fog leaves it alone and the
        # SkyLight real-time capture treats it as sky lighting.
        try_set(base, "shading_model", unreal.MaterialShadingModel.MSM_UNLIT)
        try_set(base, "two_sided", True)
        try_set(base, "is_sky", True)

        coord = mel.create_material_expression(
            base, unreal.MaterialExpressionTextureCoordinate, -1100, 0)
        try_set(coord, "u_tiling", cfg["star_tiling"][0])
        try_set(coord, "v_tiling", cfg["star_tiling"][1])

        stars = mel.create_material_expression(
            base, unreal.MaterialExpressionTextureSampleParameter2D, -820, 0)
        try_set(stars, "parameter_name", "StarsTexture")
        stars_tex = editor_asset_sub.load_asset("/Engine/EngineSky/T_Sky_Stars.T_Sky_Stars")
        if stars_tex:
            try_set(stars, "texture", stars_tex)
        else:
            unreal.log_error("[GEN]   Missing star texture /Engine/EngineSky/T_Sky_Stars.T_Sky_Stars")
        mel.connect_material_expressions(coord, "", stars, "UVs")

        brightness = mel.create_material_expression(
            base, unreal.MaterialExpressionScalarParameter, -820, 300)
        try_set(brightness, "parameter_name", "StarBrightness")
        try_set(brightness, "default_value", cfg["star_brightness"])

        star_mul = mel.create_material_expression(
            base, unreal.MaterialExpressionMultiply, -520, 60)
        mel.connect_material_expressions(stars, "", star_mul, "A")
        mel.connect_material_expressions(brightness, "", star_mul, "B")

        night_col = mel.create_material_expression(
            base, unreal.MaterialExpressionVectorParameter, -520, 320)
        try_set(night_col, "parameter_name", "NightSkyColor")
        try_set(night_col, "default_value", linear(cfg["night_sky_color"]))

        add = mel.create_material_expression(
            base, unreal.MaterialExpressionAdd, -240, 140)
        mel.connect_material_expressions(star_mul, "", add, "A")
        mel.connect_material_expressions(night_col, "", add, "B")
        mel.connect_material_property(add, "", unreal.MaterialProperty.MP_EMISSIVE_COLOR)

        mel.recompile_material(base)
        editor_asset_sub.save_loaded_asset(base)

    # Instance carries the tweakable star brightness / night sky tint
    mi_name = "MI_NightSky_Starfield"
    mi_pkg = "/Game/Forest/Materials/Instances"
    mi_path = mi_pkg + "/" + mi_name
    mi = editor_asset_sub.load_asset(mi_path + "." + mi_name)
    if not mi:
        mi = asset_tools.create_asset(
            mi_name, mi_pkg, unreal.MaterialInstanceConstant,
            unreal.MaterialInstanceConstantFactoryNew()
        )
    try_set(mi, "parent", base)
    mel.set_material_instance_scalar_parameter_value(
        mi, "StarBrightness", cfg["star_brightness"])
    mel.set_material_instance_vector_parameter_value(
        mi, "NightSkyColor", linear(cfg["night_sky_color"]))
    editor_asset_sub.save_loaded_asset(mi)
    return mi

# Directional Light (sun or moon) driving the Sky Atmosphere
sun_cfg = LIGHTING["sun"]
if sun_cfg["enabled"]:
    sun = editor_actor_sub.spawn_actor_from_class(
        unreal.DirectionalLight,
        unreal.Vector(0, 0, 5000),
        unreal.Rotator(pitch=sun_cfg["pitch"], yaw=sun_cfg["yaw"], roll=0),
    )
    sun.set_actor_label(f"{LEVEL_NAME}_{sun_cfg['label_suffix']}")
    sun_comp = sun.get_component_by_class(unreal.DirectionalLightComponent)
    if sun_comp:
        sun_comp.set_editor_property("intensity", sun_cfg["intensity"])
        sun_comp.set_editor_property("light_color", srgb(sun_cfg["color"]))
        sun_comp.set_editor_property("cast_shadows", sun_cfg["cast_shadows"])
        # r.AllowStaticLighting=False, so the engine reads the movable
        # distance even though the light is Stationary.
        sun_comp.set_editor_property("dynamic_shadow_distance_movable_light",
                                     sun_cfg["shadow_distance_cm"])
        sun_comp.set_editor_property("atmosphere_sun_light", True)
        sun_comp.set_editor_property("atmosphere_sun_light_index", 0)
    unreal.log_warning(
        f"[GEN]   {sun_cfg['label_suffix']}: {sun_cfg['intensity']} lux "
        f"@ pitch {sun_cfg['pitch']}"
    )

# SkyAtmosphere Component / Actor
sky_atmo = editor_actor_sub.spawn_actor_from_class(
    unreal.SkyAtmosphere,
    unreal.Vector(0, 0, 0),
    unreal.Rotator(0, 0, 0),
)
sky_atmo.set_actor_label(f"{LEVEL_NAME}_SkyAtmosphere")

# VolumetricCloud Actor (clear sky at night so stars stay visible)
cloud_cfg = LIGHTING["volumetric_cloud"]
if cloud_cfg["enabled"]:
    vol_cloud = editor_actor_sub.spawn_actor_from_class(
        unreal.VolumetricCloud,
        unreal.Vector(0, 0, 0),
        unreal.Rotator(0, 0, 0),
    )
    vol_cloud.set_actor_label(f"{LEVEL_NAME}_VolumetricCloud")
    vc_comp = vol_cloud.get_component_by_class(unreal.VolumetricCloudComponent)
    if vc_comp:
        cloud_mat = editor_asset_sub.load_asset("/Engine/EngineSky/VolumetricClouds/m_SimpleVolumetricCloud_Inst.m_SimpleVolumetricCloud_Inst")
        if cloud_mat:
            vc_comp.set_editor_property("material", cloud_mat)
else:
    unreal.log_warning("[GEN]   Volumetric clouds disabled for this preset")

# Sky Dome Mesh — daytime gradient, or the emissive starfield at night
dome_cfg = LIGHTING["sky_dome"]
if dome_cfg["enabled"]:
    sky_sphere_mesh = editor_asset_sub.load_asset("/Engine/EngineSky/SM_SkySphere.SM_SkySphere")
    if dome_cfg.get("build_starfield"):
        sky_sphere_mat = ensure_starfield_material(dome_cfg)
    else:
        mat_path = dome_cfg["material"]
        sky_sphere_mat = editor_asset_sub.load_asset(mat_path)
    if sky_sphere_mesh:
        sky_sphere = editor_actor_sub.spawn_actor_from_class(
            unreal.StaticMeshActor,
            unreal.Vector(0, 0, 0),
            unreal.Rotator(0, 0, 0),
        )
        sky_sphere.set_actor_label(f"{LEVEL_NAME}_SkySphere")
        ss_comp = sky_sphere.get_component_by_class(unreal.StaticMeshComponent)
        if ss_comp:
            ss_comp.set_static_mesh(sky_sphere_mesh)
            if sky_sphere_mat:
                ss_comp.set_material(0, sky_sphere_mat)
            else:
                unreal.log_error("[GEN]   Sky dome material failed to load!")
            ss_comp.set_editor_property("relative_scale3d", unreal.Vector(400.0, 400.0, 400.0))
            ss_comp.set_collision_profile_name("NoCollision")
            ss_comp.set_collision_enabled(unreal.CollisionEnabled.NO_COLLISION)
            ss_comp.set_editor_property("cast_shadow", False)

# Sky Light with Real Time Capture — at night this captures the emissive
# starfield dome, so the stars themselves are the ambient light source.
sky_cfg = LIGHTING["sky_light"]
sky = editor_actor_sub.spawn_actor_from_class(
    unreal.SkyLight,
    unreal.Vector(0, 0, 5000),
    unreal.Rotator(0, 0, 0),
)
sky.set_actor_label(f"{LEVEL_NAME}_SkyLight")
sky_comp = sky.get_component_by_class(unreal.SkyLightComponent)
if sky_comp:
    sky_comp.set_editor_property("intensity", sky_cfg["intensity"])
    sky_comp.set_editor_property("real_time_capture", sky_cfg["real_time_capture"])

# Exponential Height Fog with volumetric fog enabled
fog_cfg = LIGHTING["fog"]
fog = editor_actor_sub.spawn_actor_from_class(
    unreal.ExponentialHeightFog,
    unreal.Vector(0, 0, 500),
    unreal.Rotator(0, 0, 0),
)
fog.set_actor_label(f"{LEVEL_NAME}_Fog")
fog_comp = fog.get_component_by_class(unreal.ExponentialHeightFogComponent)
if fog_comp:
    fog_comp.set_editor_property("enable_volumetric_fog", fog_cfg["enable_volumetric"])
    try_set(fog_comp, "fog_density", fog_cfg["density"])
    # UE 5.4+ renamed this to fog_inscattering_luminance
    try_set_first(fog_comp,
                  ["fog_inscattering_luminance", "fog_inscattering_color"],
                  linear(fog_cfg["inscattering_color"]))
    try_set(fog_comp, "volumetric_fog_extinction_scale",
            fog_cfg["volumetric_extinction_scale"])

# Post Process Volume
pp_cfg = LIGHTING["post_process"]
ppv = editor_actor_sub.spawn_actor_from_class(
    unreal.PostProcessVolume,
    unreal.Vector(0, 0, 0),
    unreal.Rotator(0, 0, 0),
)
ppv.set_actor_label(f"{LEVEL_NAME}_PostProcess")
ppv.set_editor_property("unbound", True)
settings = ppv.get_editor_property("settings")
settings.set_editor_property("auto_exposure_method", unreal.AutoExposureMethod.AEM_HISTOGRAM)
settings.set_editor_property("auto_exposure_min_brightness",
                             pp_cfg["auto_exposure_min_brightness"])
settings.set_editor_property("auto_exposure_max_brightness",
                             pp_cfg["auto_exposure_max_brightness"])
settings.set_editor_property("auto_exposure_bias", pp_cfg["auto_exposure_bias"])
ppv.set_editor_property("settings", settings)

# ── 5. Plant trees ───────────────────────────────────────────────────
unreal.log_warning("[GEN] 5. Planting trees...")

TREE_DATA = [{"spec": "HISM_Tree_Leafy_Island_01", "x": 1591.33, "y": 252.15, "z": -5.05, "yaw": 80.36, "scale": 2.44}, {"spec": "HISM_Tree_Leafy_Island_01", "x": -777.55, "y": -1567.18, "z": 63.76, "yaw": 31.3, "scale": 3.427}, {"spec": "HISM_Tree_Leafy_Island_01", "x": 1278.5, "y": 242.2, "z": -23.18, "yaw": 181.93, "scale": 2.35}, {"spec": "HISM_Tree_Leafy_Island_01", "x": 233.12, "y": 700.02, "z": -54.1, "yaw": 196.18, "scale": 3.04}, {"spec": "HISM_Tree_Leafy_Island_02", "x": -858.75, "y": -539.44, "z": -60.14, "yaw": 2.34, "scale": 3.295}, {"spec": "HISM_Tree_Leafy_Island_02", "x": -591.66, "y": -1751.03, "z": 88.55, "yaw": 55.97, "scale": 2.544}, {"spec": "HISM_Tree_Leafy_Island_02", "x": -1068.42, "y": 1765.98, "z": 145.96, "yaw": 34.82, "scale": 2.148}, {"spec": "HISM_Tree_Leafy_Island_02", "x": -1516.67, "y": -1157.13, "z": 53.07, "yaw": 262.7, "scale": 3.291}, {"spec": "HISM_Tree_Fir_A", "x": 1443.29, "y": -246.14, "z": -24.74, "yaw": 198.73, "scale": 2.557}, {"spec": "HISM_Tree_Fir_A", "x": -1383.77, "y": -1275.44, "z": 48.36, "yaw": 207.85, "scale": 3.523}, {"spec": "HISM_Tree_Fir_A", "x": 1633.87, "y": 483.87, "z": 30.27, "yaw": 104.18, "scale": 2.256}, {"spec": "HISM_Tree_Fir_A", "x": 87.81, "y": 808.95, "z": -42.6, "yaw": 100.07, "scale": 2.002}, {"spec": "HISM_Tree_Fir_A", "x": -1060.7, "y": 1205.69, "z": 34.92, "yaw": 75.42, "scale": 2.54}, {"spec": "HISM_Tree_Fir_A", "x": 995.99, "y": -418.76, "z": -40.85, "yaw": 219.29, "scale": 3.096}, {"spec": "HISM_Tree_Pine_A", "x": -123.43, "y": -935.77, "z": -20.6, "yaw": 136.6, "scale": 3.409}, {"spec": "HISM_Tree_Pine_A", "x": -1345.01, "y": -1625.84, "z": 155.83, "yaw": 246.46, "scale": 4.392}, {"spec": "HISM_Tree_Deciduous", "x": 309.18, "y": -1875.75, "z": 86.71, "yaw": 11.56, "scale": 2.889}, {"spec": "HISM_Tree_Deciduous", "x": -127.87, "y": 1142.39, "z": -21.34, "yaw": 339.45, "scale": 2.859}]

# Tree spec → mesh/material config
TREE_CONFIGS = json.loads(r"""{"HISM_Tree_Leafy_Island_01": {"mesh": "/Game/Forest/Trees/SM_IslandTree_01.SM_IslandTree_01", "mats": ["/Game/Forest/Materials/Instances/MI_IslandTree01_Trunk", "/Game/Forest/Materials/Instances/MI_IslandTree01_Leaves", "/Game/Forest/Materials/Instances/MI_IslandTree01_Branches"]}, "HISM_Tree_Leafy_Island_02": {"mesh": "/Game/Forest/Trees/SM_IslandTree_02.SM_IslandTree_02", "mats": ["/Game/Forest/Materials/Instances/MI_IslandTree02_Trunk", "/Game/Forest/Materials/Instances/MI_IslandTree02_Leaves", "/Game/Forest/Materials/Instances/MI_IslandTree02_Branches"]}, "HISM_Tree_Fir_A": {"mesh": "/Game/Forest/Trees/SM_Fir_A.SM_Fir_A", "mats": ["/Game/Forest/Materials/Instances/MI_FirTree01_Bark", "/Game/Forest/Materials/Instances/MI_FirTree01_TrunkA", "/Game/Forest/Materials/Instances/MI_FirTree01_Twig", "/Game/Forest/Materials/Instances/MI_FirTree01_Bark"]}, "HISM_Tree_Pine_A": {"mesh": "/Game/Forest/Trees/SM_PineSapling_A.SM_PineSapling_A", "mats": ["/Game/Forest/Materials/Instances/MI_PineSapling_Bark", "/Game/Forest/Materials/Instances/MI_PineSapling_Twig"]}, "HISM_Tree_Deciduous": {"mesh": "/Game/Forest/Trees/SM_TreeSmall_02.SM_TreeSmall_02", "mats": ["/Game/Forest/Materials/Instances/MI_TreeSmall02_Branches", "/Game/Forest/Materials/Instances/MI_TreeSmall02_Leaves", "/Game/Forest/Materials/Instances/MI_TreeSmall02_Trunk"]}}""")

# Per-cell HISMs with a cull distance, kept on Nanite -- see
# forest_import/trees.py and forest_generator/tree_cells.py.
if r"/Users/alexeysukhov/Documents/Unreal Projects/Otherworld/Scripts" not in sys.path:
    sys.path.insert(0, r"/Users/alexeysukhov/Documents/Unreal Projects/Otherworld/Scripts")
from forest_import import trees as trees_import
# The trees planted from a copy of a scan -- see
# forest_import/tree_assets.py. Built once, then skipped.
from forest_import import tree_assets
tree_assets.ensure_tree_assets()
trees_import.plant_trees(TREE_DATA, TREE_CONFIGS, editor_actor_sub,
                         editor_asset_sub)

# ── 5a. Build the generated grass and bush meshes ────────────────────
# Opaque Nanite patches and bushes, rebuilt in place every import --
# see forest_import/foliage_assets.py.
GRASS_DATA_PATH = r"/Users/alexeysukhov/Documents/Unreal Projects/Otherworld/Scripts/generated_levels/Lvl_Probe_50m/grass_Lvl_Probe_50m.json"
EXPECTED_GRASS_COUNT = 0
EXPECTED_BUSH_COUNT = 0
GRASS_CONFIGS = json.loads(r"""{"HISM_Grass_Patch_A": {"mesh": "/Game/Forest/Procedural/SM_GrassPatch_A.SM_GrassPatch_A", "mats": ["/Game/Forest/Procedural/MI_ProcGrass"]}, "HISM_Grass_Patch_B": {"mesh": "/Game/Forest/Procedural/SM_GrassPatch_B.SM_GrassPatch_B", "mats": ["/Game/Forest/Procedural/MI_ProcGrass"]}}""")
BUSH_CONFIGS = json.loads(r"""{"HISM_Bush_Round": {"mesh": "/Game/Forest/Procedural/SM_Bush_Round.SM_Bush_Round", "mats": ["/Game/Forest/Procedural/MI_ProcBush"]}, "HISM_Bush_Tall": {"mesh": "/Game/Forest/Procedural/SM_Bush_Tall.SM_Bush_Tall", "mats": ["/Game/Forest/Procedural/MI_ProcBush"]}}""")
if EXPECTED_GRASS_COUNT > 0 or EXPECTED_BUSH_COUNT > 0:
    unreal.log_warning("[GEN] 5a. Building generated grass and bush meshes...")
    from forest_import import foliage_assets
    foliage_assets.ensure_foliage_assets()

# ── 5b. Plant knee-high grass ────────────────────────────────────────
# Per-cell, per-tier HISMs, saved unlit and (above Low) hidden in game
# -- see forest_import/grass.py and forest_generator/grass_cells.py.

if EXPECTED_GRASS_COUNT > 0 and os.path.isfile(GRASS_DATA_PATH):
    unreal.log_warning("[GEN] 5b. Planting knee-high grass...")
    if r"/Users/alexeysukhov/Documents/Unreal Projects/Otherworld/Scripts" not in sys.path:
        sys.path.insert(0, r"/Users/alexeysukhov/Documents/Unreal Projects/Otherworld/Scripts")
    from forest_import import grass as grass_import
    total_grass, grass_cells = grass_import.plant_grass(
        GRASS_DATA_PATH, GRASS_CONFIGS, editor_actor_sub, editor_asset_sub)
    unreal.log_warning(
        f"[GEN] Planted {total_grass} grass clumps in "
        f"{grass_cells} cell actors!")
else:
    unreal.log_warning("[GEN] 5b. Grass skipped (none generated).")

# ── 5c. Plant walk-through bushes ────────────────────────────────────
if EXPECTED_BUSH_COUNT > 0 and os.path.isfile(GRASS_DATA_PATH):
    unreal.log_warning("[GEN] 5c. Planting bushes...")
    from forest_import import bushes as bushes_import
    bushes_import.plant_bushes(GRASS_DATA_PATH, BUSH_CONFIGS,
                               editor_actor_sub, editor_asset_sub)
else:
    unreal.log_warning("[GEN] 5c. Bushes skipped (none generated).")

# ── 6. Spawn Player Start ────────────────────────────────────────────
unreal.log_warning("[GEN] 6. Spawning player start...")
ps = editor_actor_sub.spawn_actor_from_class(
    unreal.PlayerStart,
    unreal.Vector(0, 0, 100),
    unreal.Rotator(0, 0, 0),
)
ps.set_actor_label(f"{LEVEL_NAME}_PlayerStart")

# ── 7. Navigation + wandering NPC ────────────────────────────────────
NPC_SPAWNS = json.loads(r"""[{"x": -317.88, "y": 1874.19, "z": 215.0, "yaw": 279.63}, {"x": 570.75, "y": 1784.48, "z": 201.93, "yaw": 252.26}, {"x": 1710.15, "y": -817.38, "z": 231.47, "yaw": 154.45}, {"x": -1608.34, "y": -861.04, "z": 178.1, "yaw": 28.16}, {"x": 1875.79, "y": 273.47, "z": 177.85, "yaw": 188.29}, {"x": -153.75, "y": -1860.9, "z": 207.54, "yaw": 85.28}, {"x": -1238.63, "y": 1528.0, "z": 235.99, "yaw": 309.03}, {"x": 1416.08, "y": 1273.33, "z": 235.21, "yaw": 221.96}, {"x": -1809.57, "y": 216.41, "z": 232.56, "yaw": 353.18}, {"x": 1395.57, "y": -1373.15, "z": 249.44, "yaw": 135.46}]""")
NAV_BOUNDS = json.loads(r"""{"half_xy_cm": 2500.0, "center_z_cm": 475.68, "half_z_cm": 723.18, "terrain_min_z_cm": -47.5, "terrain_max_z_cm": 998.86}""")
SCRIPTS_DIR = r"/Users/alexeysukhov/Documents/Unreal Projects/Otherworld/Scripts"
NAV_AGENT_RADIUS = 35.0
NAV_AGENT_HEIGHT = 144.0

if NPC_SPAWNS:
    unreal.log_warning(
        f"[GEN] 7. Building navigation and spawning "
        f"{len(NPC_SPAWNS)} NPC(s)...")

    # NavMeshBoundsVolume's default brush is a 200 cm cube, so scaling
    # the actor by world_size/200 makes it cover the map exactly.
    # Sized from the terrain band the NPC can actually walk on, NOT
    # from the map width.  Recast voxelises the full height of every
    # tile, so an over-tall volume silently yields no tiles at all and
    # nothing is ever navigable.
    nav_volume = editor_actor_sub.spawn_actor_from_class(
        unreal.NavMeshBoundsVolume,
        unreal.Vector(0.0, 0.0, NAV_BOUNDS["center_z_cm"]))
    nav_volume.set_actor_label(f"{LEVEL_NAME}_NavBounds")
    # The default brush is a 200 cm cube, i.e. 100 cm half-extent.
    nav_volume.set_actor_scale3d(unreal.Vector(
        NAV_BOUNDS["half_xy_cm"] / 100.0,
        NAV_BOUNDS["half_xy_cm"] / 100.0,
        NAV_BOUNDS["half_z_cm"] / 100.0,
    ))

    # Deliberately do NOT place a RecastNavMesh actor.
    #
    # A headless editor never finishes an async navmesh bake, so any
    # RecastNavMesh saved from here carries EMPTY serialised tile data.
    # At game start the engine finds that data structurally valid and
    # reuses it instead of building -- 0 tiles, every MoveTo fails, and
    # the NPC never moves.  It only ever appeared to work right after a
    # nav-bounds change, because the changed parameters no longer matched
    # the serialised ones and the engine logged
    #   "Recreating dtNavMesh instance ... due mismatch in ... maxTiles"
    # and rebuilt.  Once the bounds settled, it silently stopped again.
    #
    # Leaving no nav data in the level makes the navigation system create
    # it at load, which always builds (324 tiles here).  Runtime
    # generation is Dynamic via Config/DefaultEngine.ini, since the nav
    # system overwrites per-actor values with class defaults anyway.
    # (the actual removal happens immediately before the save below --
    #  the navigation system re-creates nav data while the level is open,
    #  so removing it any earlier accomplishes nothing)

    # The NPC Blueprints are level-independent, so they live in their
    # own idempotent builder script rather than being re-emitted here.
    if SCRIPTS_DIR not in sys.path:
        sys.path.insert(0, SCRIPTS_DIR)
    import build_npc_blueprints
    from forest_generator.npc_placement import (
gait_scale_for_index, variant_for_index)
    # force=True: the builder updates assets IN PLACE and is idempotent,
    # so re-running it is cheap -- and without it an existing
    # BP_ForestWanderer is reused wholesale and no property change in
    # build_npc_blueprints.py ever reaches the asset via this path.
    npc_variants = build_npc_blueprints.ensure_npc_variants(force=True)
    npc_classes = {
        key: unreal.BlueprintEditorLibrary.generated_class(bp)
        for key, bp in npc_variants.items()
    }

    # One actor per spawn point, labelled _NPC_Wanderer_<creature>_<n>.
    # The labels are what verify_<Level>.py matches on: it filters on
    # the _NPC_Wanderer prefix and sorts on the TRAILING number, so the
    # creature name goes in the middle -- appended, it would be read as
    # the index, every wanderer would sort as 0, and the pairwise
    # position checks would compare each NPC against the wrong spawn.
    # 1-based to line up with the generator's own console output.
    for i, spawn in enumerate(NPC_SPAWNS, start=1):
        variant = variant_for_index(i)
        npc_actor = editor_actor_sub.spawn_actor_from_class(
            npc_classes[variant.key],
            unreal.Vector(spawn["x"], spawn["y"], spawn["z"]),
            # Keywords, not positional: unreal.Rotator is (roll, pitch, yaw).
            unreal.Rotator(pitch=0.0, yaw=spawn["yaw"], roll=0.0),
        )
        npc_actor.set_actor_label(
            f"{LEVEL_NAME}_NPC_Wanderer_{variant.key}_{i}")

        # Break the lockstep, and keep the stride planted.
        #
        # TWO factors multiply into the animation rate and only one of
        # them into the speed here, because the other is already in it:
        # the variant Blueprint carries its own MaxWalkSpeed (the
        # wendigo runs at 690), so reading and scaling that applies the
        # gait on top of a speed that is already right. The anim rate
        # has no such starting point -- it is 1.0 on every variant --
        # so it has to be told about both.
        #
        # Getting that wrong is foot-sliding: the locomotion blend
        # space is authored for a ground speed, so a wendigo covering
        # 15% more ground per second at a zombie's stride rate skates.
        gait = gait_scale_for_index(i)
        rate = gait * variant.speed_scale
        npc_actor.get_editor_property("mesh").set_editor_property(
            "global_anim_rate_scale", rate)
        move = npc_actor.get_editor_property("character_movement")
        move.set_editor_property(
            "max_walk_speed",
            move.get_editor_property("max_walk_speed") * gait)
        unreal.log_warning(
            f"[GEN]    NPC {i} ({variant.key}) at ({spawn['x']:.0f}, "
            f"{spawn['y']:.0f}, {spawn['z']:.0f}) -- "
            f"{move.get_editor_property('max_walk_speed'):.0f} cm/s, "
            f"anim x{rate:.3f}")
    unreal.log_warning(
        "[GEN]    navmesh is built by the navigation system at game "
        "start (no nav data saved in the level)")
    unreal.log_warning(
        f"[GEN]    Nav volume: +/-{NAV_BOUNDS['half_xy_cm']:.0f} cm XY, "
        f"Z span {NAV_BOUNDS['half_z_cm'] * 2.0:.0f} cm "
        f"centred {NAV_BOUNDS['center_z_cm']:.0f}")
else:
    unreal.log_warning("[GEN] 7. NPCs skipped (none placed).")

# ── 8. Save ─────────────────────────────────────────────────────────
# Strip nav data as the very last action: the navigation system
# re-creates a RecastNavMesh whenever the level is open, and anything
# saved here carries EMPTY serialised tiles that the game then reuses
# instead of building (see section 7).
stripped = 0
for a in list(editor_actor_sub.get_all_level_actors()):
    if isinstance(a, unreal.RecastNavMesh):
        editor_actor_sub.destroy_actor(a)
        stripped += 1
unreal.log_warning(f"[GEN] Stripped {stripped} RecastNavMesh actor(s) before save")
level_editor_sub.save_current_level()
unreal.log_warning("=" * 60)
unreal.log_warning(f"[GEN] ✅ {LEVEL_NAME} GENERATED AND SAVED!")
unreal.log_warning("=" * 60)
