"""Engine properties and components the graphs read through a variable node:
the name each is known by on its engine class."""

BLEND_WEIGHT = "BlendWeight"
BRAIN_COMPONENT = "BrainComponent"
BRAKING_DECELERATION_WALKING = "BrakingDecelerationWalking"
CAPSULE_COMPONENT = "CapsuleComponent"
CHARACTER_MOVEMENT = "CharacterMovement"
CROUCHED_HALF_HEIGHT = "CrouchedHalfHeight"
CURRENT_FLOOR = "CurrentFloor"
FIELD_OF_VIEW = "FieldOfView"
IS_CROUCHED = "bIsCrouched"
MAX_WALK_SPEED = "MaxWalkSpeed"
MAX_WALK_SPEED_CROUCHED = "MaxWalkSpeedCrouched"
MESH = "Mesh"
ORIENT_ROTATION_TO_MOVEMENT = "bOrientRotationToMovement"
PLAYER_CAMERA_MANAGER = "PlayerCameraManager"
STATIC_MESH = "StaticMesh"
