"""The test garments: one of each laid in a row on the ground in front of the
PlayerStart of the 200 m map, so a new game opens facing them.

Placed into the level and saved, as the forage is (survival/forage_level.py,
whose terrain-mesh heights this reuses: a trace in a level loaded in the same
Python call misses). Every placed actor carries TEST_TAG and is deleted and
placed again on each run, so the pass is idempotent; a level regenerated by
its import_<Level>.py loses them, and build_clothing.py puts them back.
"""

import math

import unreal

from combat.graph import _log
from clothing.specs import GARMENTS
from survival.forage_level import _terrain_heights

TEST_LEVEL = "/Game/Maps/Lvl_Forest_200m"
TEST_TAG = "OW_TestClothing"
AHEAD_CM = 300.0        # how far in front of the PlayerStart the row lies
SPACING_CM = 55.0       # between two garments, across the view
LIFT_CM = 1.0           # on the ground, not in it


def row_spots(start_xy, yaw_deg, count=len(GARMENTS)):
    """(x, y) of each garment: a row across the view, AHEAD_CM out. Pure."""
    yaw = math.radians(yaw_deg)
    fx, fy = math.cos(yaw), math.sin(yaw)
    rx, ry = -fy, fx
    mid = (count - 1) / 2.0
    return [(start_xy[0] + fx * AHEAD_CM + rx * SPACING_CM * (i - mid),
             start_xy[1] + fy * AHEAD_CM + ry * SPACING_CM * (i - mid))
            for i in range(count)]


def _sub():
    return unreal.get_editor_subsystem(unreal.EditorActorSubsystem)


def place_test_clothing(level_path=TEST_LEVEL):
    """Replace the level's test garments and save it. Returns how many."""
    les = unreal.get_editor_subsystem(unreal.LevelEditorSubsystem)
    if not les.load_level(level_path):
        raise RuntimeError(f"could not load {level_path}")
    sub = _sub()
    actors = sub.get_all_level_actors()
    stale = [a for a in actors if a.actor_has_tag(TEST_TAG)]
    if stale:
        sub.destroy_actors(stale)
    actors = [a for a in actors if a not in stale]

    start = next((a for a in actors if isinstance(a, unreal.PlayerStart)), None)
    terrain = next((a for a in actors if a.get_actor_label().endswith("_Terrain")), None)
    if start is None or terrain is None:
        raise RuntimeError(f"{level_path} has no PlayerStart or *_Terrain actor")
    at = start.get_actor_location()
    yaw = start.get_actor_rotation().yaw
    heights = _terrain_heights(terrain.get_editor_property("static_mesh_component"))
    for garment, (x, y) in zip(GARMENTS, row_spots((at.x, at.y), yaw)):
        z = heights.height(x, y)
        if z is None:
            raise RuntimeError(f"{level_path}: the {garment.display} is off the terrain")
        actor = sub.spawn_actor_from_class(
            unreal.load_class(None, garment.class_path),
            unreal.Vector(x, y, z + LIFT_CM),
            unreal.Rotator(roll=0.0, pitch=0.0, yaw=yaw + 180.0))
        actor.set_actor_label(f"TestClothing_{garment.display}")
        actor.set_editor_property("tags", [unreal.Name(TEST_TAG)])
    if not les.save_current_level():
        raise RuntimeError(f"could not save {level_path}")
    _log(f"{level_path}: {len(GARMENTS)} test garments {AHEAD_CM / 100:.0f} m in front "
         f"of the PlayerStart ({len(stale)} old ones removed)")
    return len(GARMENTS)


def test_clothing_in_level(level_path=TEST_LEVEL):
    """The test garments in the level now (for the verifier)."""
    les = unreal.get_editor_subsystem(unreal.LevelEditorSubsystem)
    if not les.load_level(level_path):
        raise RuntimeError(f"could not load {level_path}")
    return [a for a in _sub().get_all_level_actors() if a.actor_has_tag(TEST_TAG)]
