"""Putting the scattered garments into a generated level, inside the editor.

The forage's pass over again (survival/forage_level.py, whose trunk positions
and terrain-mesh heights this reuses): it reads the level as built, the
terrain actor, the tree cells and the PlayerStart, and keeps clear of the
forage already lying there, so it runs after place_forage.py. Every placed
actor carries SCATTER_TAG and is deleted and placed again on each run, so the
pass is idempotent; a level regenerated by its import_<Level>.py loses them,
and build_clothing.py puts them back. The test row (placement.py) has its own
tag and is not touched.
"""

import os
import random

import unreal

from combat.log import _log
from clothing.scatter import SCATTER_SEED, scatter_clothing
from clothing.specs import GARMENTS
from survival.forage_level import FORAGE_TAG, _terrain_heights, _trunks
from world.level_save import save_level

SCATTER_TAG = "OW_Clothing"
LIFT_CM = 1.0           # on the ground, not in it
_GENERATED = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..",
                          "generated_levels")


def scatter_levels():
    """Every level the generator has produced that also exists as a map."""
    return sorted(f"/Game/Maps/{name}" for name in os.listdir(_GENERATED)
                  if unreal.EditorAssetLibrary.does_asset_exist(f"/Game/Maps/{name}"))


def _sub():
    return unreal.get_editor_subsystem(unreal.EditorActorSubsystem)


def place_scattered_clothing(level_path):
    """Replace this level's scattered garments and save it. Returns
    {display: count placed}."""
    les = unreal.get_editor_subsystem(unreal.LevelEditorSubsystem)
    if not les.load_level(level_path):
        raise RuntimeError(f"could not load {level_path}")
    sub = _sub()
    actors = sub.get_all_level_actors()
    stale = [a for a in actors if a.actor_has_tag(SCATTER_TAG)]
    if stale:
        sub.destroy_actors(stale)
    actors = [a for a in actors if a not in stale]

    terrain = next((a for a in actors if a.get_actor_label().endswith("_Terrain")), None)
    if terrain is None:
        raise RuntimeError(f"{level_path} has no *_Terrain actor")
    origin, extent = terrain.get_actor_bounds(False)
    start = next((a for a in actors if isinstance(a, unreal.PlayerStart)), None)
    start_xy = ((start.get_actor_location().x, start.get_actor_location().y)
                if start else (origin.x, origin.y))
    forage = [(a.get_actor_location().x, a.get_actor_location().y)
              for a in actors if a.actor_has_tag(FORAGE_TAG)]
    spots = scatter_clothing((origin.x - extent.x, origin.x + extent.x),
                             (origin.y - extent.y, origin.y + extent.y),
                             _trunks(actors), start_xy, forage)

    heights = _terrain_heights(terrain.get_editor_property("static_mesh_component"))
    classes = {g.display: unreal.load_class(None, g.class_path) for g in GARMENTS}
    rng = random.Random(SCATTER_SEED)
    placed, missed = {}, 0
    for display, x, y in spots:
        z = heights.height(x, y)
        if z is None:
            missed += 1
            continue
        actor = sub.spawn_actor_from_class(
            classes[display], unreal.Vector(x, y, z + LIFT_CM),
            unreal.Rotator(roll=0.0, pitch=0.0, yaw=rng.uniform(0.0, 360.0)))
        n = placed.get(display, 0) + 1
        placed[display] = n
        actor.set_actor_label(f"Clothing_{display}_{n:03d}")
        actor.set_editor_property("tags", [unreal.Name(SCATTER_TAG)])
    if missed:
        raise RuntimeError(f"{level_path}: {missed} garment spots are off the "
                           "terrain mesh; nothing saved")
    save_level(level_path)
    _log(f"{level_path}: scattered {placed} ({len(stale)} old ones removed)")
    return placed


def scattered_in_level(level_path):
    """The scattered garments in the level now (for the verifier)."""
    les = unreal.get_editor_subsystem(unreal.LevelEditorSubsystem)
    if not les.load_level(level_path):
        raise RuntimeError(f"could not load {level_path}")
    return [a for a in _sub().get_all_level_actors() if a.actor_has_tag(SCATTER_TAG)]
