"""BP_ForestWandererAI and its per-creature copies: on possession, run this
controller's Behavior Tree (npc/tree.py), whose steps are the controller's
BT_* events (npc/steps.py); plus the creature's sounds and hit reactions.
"""

import unreal

from forest_generator.npc_placement import NPC_VARIANTS
from forest_generator.npc_stalk import NPC_STALK_ROAR
from npc.paths import (
    AI_BP_PATH, HIT_DAMAGE_VAR, HIT_SOUNDS, HIT_SOUNDS_VAR, REACTIONS_VAR,
    STEP_CHASE, STEP_PRESENT, STEP_PULSE, STEP_STALK, STEP_STROLL, STEP_SWING,
    STEP_WARD, VOICES_VAR,
    step_task_path, tree_path,
)
from npc.nodes import FN_RUN_BT, NODE_EVENT_POSSESS
from npc.graph import (
    _asset_sub, _at, BEL, BGE, _connect, _create_blueprint, _log, _node,
    _palette, _set,
)
from npc.sight_cone import _author_sight_cone
from npc.step_task import build_step_task, clear_step_task
from npc.steps import _author_steps
from npc.tree import build_blackboard, fill_tree, fresh_tree
from npc.monster_tuning import monster_specs
from npc.tuned import write_tuned_defaults
from npc.ward import wards


def build_ai_controller_blueprint(rebuild=True, path=None, melee_anim=None,
                                 voices=(), hit_sounds=HIT_SOUNDS, reactions=(),
                                 key=None):
    """Create an AI controller and author its patrol, senses, chase and attack.

    ``key`` is the creature (NPC_VARIANTS); None means the base creature,
    which is what the parent controller wears. Its numbers -- senses, patrol,
    speed, melee, health -- are npc/monster_tuning.monster_specs(key), baked
    as the defaults of the controller's Tune* variables (npc/tuned.py).

    ``rebuild`` wipes the graph first.  It defaults to True because this builder
    is the only description of the behaviour: the old "already authored,
    reusing" guard meant no edit here ever reached the asset once it existed.

    ``path``, ``melee_anim``, ``key`` and ``voices`` exist because all four
    are per creature.  The attack clip is per creature because
    each monster now has its own skeleton (see import_characters.py), and an
    AnimSequence belongs to exactly one skeleton, so a single controller cannot
    hold a literal that plays on both a zombie and a wendigo.  ``key`` picks
    the creature's numbers: a wendigo has three times a zombie's health, and the
    controller is the only place that can reach an inherited component's
    defaults per child (see _author_stats_and_voice).  ``voices`` because a
    zombie growls and a wendigo roars.

    A controller per variant is one way to solve that, and it is what this
    does.  Both are generated by THIS function from the same constants, so the
    melee numbers cannot drift between them the way two hand-authored graphs
    would.

    It is not the only way, and probably not the best one.  The alternative --
    an AnimSequence variable on the pawn, overridden per child Blueprint, read
    by one shared controller -- was ruled out on the false belief that Python
    cannot declare object-reference variables.  It can:
    BlueprintEditorLibrary.get_object_reference_type, which
    build_weapons_and_combat.py already uses for FireSound and AimPose.  That
    route would need the pawn Blueprint to exist before the controller graph is
    authored (they are currently built the other way round) and a cast to read
    the variable, so it is a real refactor rather than a rename -- worth doing
    when a third creature makes the duplication cost something.
    """
    path = path or AI_BP_PATH
    key = key or NPC_VARIANTS[0].key
    spec = monster_specs(key)
    bb = build_blackboard()
    bp = _create_blueprint(path, unreal.AIController)
    ed = BGE.get_graph_editor_by_name(bp, "EventGraph")
    if not ed:
        raise RuntimeError(f"{path} has no EventGraph")

    authored = bool(ed.find_event_node("ReceivePossess"))
    if authored and not rebuild:
        _log(f"{path} graph already authored — reusing")
        if not BEL.compile_blueprint(bp):
            raise RuntimeError(f"{path} failed to compile")
        _asset_sub().save_loaded_asset(bp)
        return bp
    _log("wiping the existing AI graph")
    clear_step_task(step_task_path(path))
    ed.remove_nodes(ed.list_all_nodes())
    # Compile the empty graph, so the step events' names are free again and
    # nothing references the old tree when fresh_tree deletes it.
    BEL.compile_blueprint(bp)
    bt = fresh_tree(tree_path(path))

    # Each NPC's swing timer. Zero is the right default -- it means "may attack
    # immediately" -- which is just as well, since add_member_variable's own
    # default-value argument silently does not apply (see CLAUDE.md).
    ed.remove_member_variable("NextAttackTime")
    if not ed.add_member_variable("NextAttackTime",
                                  BEL.get_basic_type_by_name("real")):
        raise RuntimeError("could not declare NextAttackTime")
    # What the swing being landed deals, after the player's guard (npc/block.py).
    ed.remove_member_variable(HIT_DAMAGE_VAR)
    if not ed.add_member_variable(HIT_DAMAGE_VAR,
                                  BEL.get_basic_type_by_name("real")):
        raise RuntimeError(f"could not declare {HIT_DAMAGE_VAR}")

    # Possession starts the tree. BeginPlay would be too early: a controller's
    # BeginPlay runs before it has possessed anything.
    possess = _palette(ed, NODE_EVENT_POSSESS, 0.0, -600.0)
    run = _at(_node(ed, FN_RUN_BT), 300, -600)
    _set(run, "BTAsset", bt.get_path_name())
    _connect(BEL.find_then_pin(possess), BEL.find_execute_pin(run))
    ed.add_comment_to_nodes(
        f"On possession, run {bt.get_name()}. The tree (npc/tree.py) decides "
        f"what this wanderer does; the BT_* events below are its steps.",
        [possess, run])

    senses = _author_steps(ed, key, melee_anim, 0, 0)
    # Debug mode's sight cone, on a Tick of its own (npc/sight_cone.py).
    _author_sight_cone(ed, -3600, -600)

    if not BEL.compile_blueprint(bp):
        raise RuntimeError(f"{path} failed to compile")

    # The sound arrays are defaults on the class, not pin literals -- an array
    # cannot be written into a pin. Missing files are dropped rather than
    # raising: /Game/Audio is built from assets/generated/sounds, which a
    # checkout that has not run Scripts/make_creature_sounds.py does not have,
    # and the graph already guards an empty array.
    eas = _asset_sub()
    cdo = unreal.get_default_object(BEL.generated_class(bp))
    for var, wanted in ((VOICES_VAR, voices), (HIT_SOUNDS_VAR, hit_sounds)):
        found = [eas.load_asset(a) for a in wanted if eas.does_asset_exist(a)]
        cdo.set_editor_property(var, found)
        if len(found) != len(wanted):
            _log(f"note: {path} {var}: {len(found)} of {len(wanted)} sounds "
                 f"exist -- run Scripts/make_creature_sounds.py, then "
                 f"build_weapons_and_combat.py, to import the rest")

    # The flinches, same mechanism, but ALL SIX OR NONE: the reaction graph
    # indexes this array by position (three Fronts, then Back, Left, Right), so
    # a partial set is not a shorter list, it is the wrong clip for three of the
    # four directions -- and that failure is silent, where an empty array simply
    # means this creature does not flinch.
    clips = [eas.load_asset(a) for a in reactions if eas.does_asset_exist(a)]
    if len(clips) != len(reactions):
        _log(f"note: {path}: {len(clips)} of {len(reactions)} hit reactions "
             f"exist -- run Scripts/asset_pipeline/build_retarget.py. This "
             f"creature will not flinch.")
        clips = []
    cdo.set_editor_property(REACTIONS_VAR, clips)
    write_tuned_defaults(cdo, spec)

    # A stalker (the wendigo) has one more step, ahead of Chase (npc/stalk.py).
    # One afraid of fire (the wendigo again) has another, ahead of the whole
    # attack (npc/ward.py).
    stalks, warded = key in NPC_STALK_ROAR, wards(key)
    task = build_step_task(bp, step_task_path(path),
                           [STEP_PULSE] + [STEP_WARD] * warded
                           + [STEP_STALK] * stalks
                           + [STEP_CHASE, STEP_SWING, STEP_PRESENT]
                           + senses + [STEP_STROLL])
    fill_tree(bt, bb, task, senses, stalks=stalks, wards=warded)
    eas.save_loaded_asset(bp)
    _log(f"built {path} ({len(cdo.get_editor_property(REACTIONS_VAR))} hit "
         f"reactions, health {spec['health']:.0f}"
         + f", {len(cdo.get_editor_property(VOICES_VAR))} voices, patrols "
         f"{spec['patrol_radius_cm'] / 100:.0f} m, sees "
         f"{spec['vision_range_cm'] / 100:.0f} m)")
    return bp
