"""BP_ForestWandererAI and its per-creature copies: the heartbeat loop that
chases, attacks, speaks and applies the creature's stats.
"""

import unreal

from forest_generator.npc_agro import agro_for
from forest_generator.npc_placement import (
    NAV_REACHABLE_EXTENT_CM, NPC_ACCEPTANCE_RADIUS_CM, NPC_BASE_HEALTH,
    NPC_MELEE_DAMAGE, NPC_MELEE_INTERVAL_S, NPC_MELEE_RANGE_CM,
    NPC_REPATH_SECONDS, NPC_VARIANTS, NPC_VOICE_MAX_S, NPC_VOICE_MIN_S,
)
from npc.paths import (
    AI_BP_PATH, HIT_SOUNDS, HIT_SOUNDS_VAR, REACTIONS_VAR, VOICES_VAR,
)
from npc.nodes import (
    FN_ACTOR_LOC, FN_AND_B, FN_DELAY, FN_GET_PAWN, FN_GET_PLAYER_PAWN,
    FN_IS_VALID, FN_MAKE_VECTOR, FN_MOVE_TO_ACTOR, FN_MOVE_TO_LOCATION,
    FN_PROJECT_NAV,
)
from npc.graph import (
    _asset_sub, _at, BEL, BGE, _connect, _create_blueprint, _log, _node,
    _palette, _pin, _set,
)
from npc.stats import _author_stats_and_voice
from npc.agro import _author_agro
from npc.corpse import _author_corpse_gate
from npc.melee import _author_melee


def build_ai_controller_blueprint(rebuild=True, path=None, melee_anim=None,
                                 health=NPC_BASE_HEALTH, voices=(),
                                 hit_sounds=HIT_SOUNDS, reactions=(),
                                 agro=None):
    """Create an AI controller and author its patrol, senses, chase and attack.

    ``agro`` is this creature's AgroSettings (forest_generator/npc_agro.py);
    None means the base creature's, which is what the parent controller wears.

    ``rebuild`` wipes the graph first.  It defaults to True because this builder
    is the only description of the behaviour: the old "already authored,
    reusing" guard meant no edit here ever reached the asset once it existed.

    ``path``, ``melee_anim``, ``health`` and ``voices`` exist because all four
    are per creature.  The attack clip is per creature because
    each monster now has its own skeleton (see import_characters.py), and an
    AnimSequence belongs to exactly one skeleton, so a single controller cannot
    hold a literal that plays on both a zombie and a wendigo.  ``health`` is
    per creature because a wendigo has three times a zombie's, and the
    controller is the only place that can reach an inherited component's
    defaults per child (see _author_stats_and_voice).  ``voices`` because a
    zombie growls and a wendigo roars.

    A controller per variant is one way to solve that, and it is what this
    does.  Both are generated by THIS function from the same constants, so the
    melee numbers cannot drift between them the way two hand-authored graphs
    would.

    It is not the only way, and probably not the best one.  The alternative --
    an AnimSequence variable on the pawn, overridden per child Blueprint, read
    by one shared controller -- was ruled out on the false belief that Python
    cannot declare object-reference variables.  It can:
    BlueprintEditorLibrary.get_object_reference_type, which
    build_weapons_and_combat.py already uses for FireSound and AimPose.  That
    route would need the pawn Blueprint to exist before the controller graph is
    authored (they are currently built the other way round) and a cast to read
    the variable, so it is a real refactor rather than a rename -- worth doing
    when a third creature makes the duplication cost something.
    """
    path = path or AI_BP_PATH
    agro = agro or agro_for(NPC_VARIANTS[0].key)
    bp = _create_blueprint(path, unreal.AIController)
    ed = BGE.get_graph_editor_by_name(bp, "EventGraph")
    if not ed:
        raise RuntimeError(f"{path} has no EventGraph")

    begin_play = ed.find_event_node("ReceiveBeginPlay")
    authored = bool(begin_play and BEL.find_then_pin(begin_play)
                    and BEL.find_then_pin(begin_play).list_connected_pins())
    if authored and not rebuild:
        _log(f"{path} graph already authored — reusing")
        if not BEL.compile_blueprint(bp):
            raise RuntimeError(f"{path} failed to compile")
        _asset_sub().save_loaded_asset(bp)
        return bp
    if authored:
        _log("wiping the existing AI graph")
        ed.remove_nodes(ed.list_all_nodes())
        begin_play = None

    if not begin_play:
        begin_play = ed.find_event_node("ReceiveBeginPlay")
    if not begin_play:
        # A fresh Blueprint ships a disabled BeginPlay placeholder, but a wiped
        # graph has none, so put one back from the palette.
        begin_play = _palette(ed, "AddEvent|EventBeginPlay", 0.0, 0.0)
    origin = BEL.get_node_pos(begin_play)

    # Each NPC's swing timer. Zero is the right default -- it means "may attack
    # immediately" -- which is just as well, since add_member_variable's own
    # default-value argument silently does not apply (see CLAUDE.md).
    ed.remove_member_variable("NextAttackTime")
    if not ed.add_member_variable("NextAttackTime",
                                  BEL.get_basic_type_by_name("real")):
        raise RuntimeError("could not declare NextAttackTime")

    move_to = _at(_node(ed, FN_MOVE_TO_ACTOR), origin.x + 1000, origin.y - 120)
    get_pawn = _at(_node(ed, FN_GET_PLAYER_PAWN), origin.x + 40, origin.y + 220)
    delay = _at(_node(ed, FN_DELAY), origin.x + 4600, origin.y)

    # Goal = the player pawn
    _set(get_pawn, "PlayerIndex", 0)
    _connect(_pin(get_pawn, "ReturnValue", is_input=False), _pin(move_to, "Goal"))

    # Pathfinding is what makes it run around the trees rather than into them.
    _set(move_to, "AcceptanceRadius", NPC_ACCEPTANCE_RADIUS_CM)
    _set(move_to, "bUsePathfinding", "true")
    _set(move_to, "bStopOnOverlap", "true")
    # Partial paths keep the NPC advancing as far as the navmesh allows instead
    # of refusing to move at all; the retry loop then re-paths, so a temporary
    # dead end does not end the chase.
    _set(move_to, "bAllowPartialPath", "true")

    _set(delay, "Duration", NPC_REPATH_SECONDS)

    # BeginPlay -> [possessed?] -> MoveToActor -> (melee) -> Delay -> back
    #
    # The gate is not defensive padding: a controller's BeginPlay runs before it
    # has possessed anything, so the first pass through the loop has no pawn.
    # MoveToActor then quietly does nothing, and the melee chain's
    # GetActorLocation reads a None pawn -- which the VM reports as an "Accessed
    # None ... CallFunc_K2_GetPawn_ReturnValue" runtime error against the swing
    # Branch, once per spawned NPC.  Note the gate has to sit *before*
    # MoveToActor rather than joining the melee AND: pure nodes are pulled by
    # whichever node reads them and BooleanAND does not short-circuit, so an
    # IsValid in the condition would still evaluate the location chain.
    #
    # Skipping the body costs one Delay -- the loop re-enters
    # NPC_REPATH_SECONDS later, by which time possession has happened.
    own_pawn = _at(_node(ed, FN_GET_PAWN), origin.x - 220, origin.y - 320)
    possessed = _at(_node(ed, FN_IS_VALID), origin.x + 40, origin.y - 320)
    _connect(_pin(own_pawn, "ReturnValue", is_input=False),
             _pin(possessed, "Object"))
    gate = _at(ed.add_branch_node(), origin.x + 300, origin.y - 200)
    _connect(_pin(possessed, "ReturnValue", is_input=False),
             _pin(gate, "Condition"))
    _connect(BEL.find_then_pin(begin_play), _pin(gate, "execute"))
    _connect(BEL.find_then_pin(delay), _pin(gate, "execute"))
    # --- can this chase be pathfound at all? ---------------------------------
    # See NAV_REACHABLE_EXTENT_CM. Both ends are tested, and both have to be
    # on the navmesh for pathfinding to be the right tool: a player who has
    # walked into the un-navigable ring cannot be pathed TO, and a wanderer
    # already standing in it cannot be pathed FROM. Either way the answer is
    # the same -- walk at them in a straight line.
    #
    # K2_ProjectPointToNavigation is pure and re-evaluates once per output pin
    # that is read. Only ReturnValue is read from each of these, so each
    # projects exactly once per frame the loop runs, and the ProjectedLocation
    # output is deliberately left dangling: the destination is the player's
    # real position, not a snapped one. Snapping it back onto the navmesh is
    # precisely the behaviour that made the dead zone.
    reach = _at(_node(ed, FN_MAKE_VECTOR), origin.x + 40, origin.y + 900)
    for axis, value in zip(("X", "Y", "Z"), NAV_REACHABLE_EXTENT_CM):
        _set(reach, axis, value)
    reach_out = _pin(reach, "ReturnValue", is_input=False)

    goal_loc = _at(_node(ed, FN_ACTOR_LOC), origin.x + 300, origin.y + 380)
    _connect(_pin(get_pawn, "ReturnValue", is_input=False), _pin(goal_loc, "self"))
    goal_out = _pin(goal_loc, "ReturnValue", is_input=False)
    goal_on = _at(_node(ed, FN_PROJECT_NAV), origin.x + 560, origin.y + 380)
    _connect(goal_out, _pin(goal_on, "Point"))
    _connect(reach_out, _pin(goal_on, "QueryExtent"))

    here_pawn = _at(_node(ed, FN_GET_PAWN), origin.x + 40, origin.y + 620)
    here_loc = _at(_node(ed, FN_ACTOR_LOC), origin.x + 300, origin.y + 620)
    _connect(_pin(here_pawn, "ReturnValue", is_input=False), _pin(here_loc, "self"))
    here_on = _at(_node(ed, FN_PROJECT_NAV), origin.x + 560, origin.y + 620)
    _connect(_pin(here_loc, "ReturnValue", is_input=False), _pin(here_on, "Point"))
    _connect(reach_out, _pin(here_on, "QueryExtent"))

    both_on = _at(_node(ed, FN_AND_B), origin.x + 800, origin.y + 500)
    _connect(_pin(goal_on, "ReturnValue", is_input=False), _pin(both_on, "A"))
    _connect(_pin(here_on, "ReturnValue", is_input=False), _pin(both_on, "B"))

    pathable = _at(ed.add_branch_node(), origin.x + 800, origin.y + 200)
    _connect(_pin(both_on, "ReturnValue", is_input=False), _pin(pathable, "Condition"))
    _connect(BEL.find_then_pin(pathable), BEL.find_execute_pin(move_to))

    # First thing with a pawn: is it a corpse? A dead wanderer's heartbeat ends
    # there, so nothing below -- stats, voice, patrol, chase, melee -- can run
    # for it. See npc/corpse.py.
    _, alive = _author_corpse_gate(ed, BEL.find_then_pin(gate),
                                   origin.x - 200, origin.y - 1400)
    # Between "a living pawn" and "can we path to the player": this creature's
    # health, applied once, and its voice on a timer. Both need the pawn, which
    # is why they sit after the gate and not on BeginPlay.
    extras, after_extras = _author_stats_and_voice(
        ed, alive, origin.x - 200, origin.y + 1400,
        health, NPC_VOICE_MIN_S, NPC_VOICE_MAX_S)
    # ...then patrol or hunt. Everything above runs for a patrolling wanderer
    # too (it still has its health and still growls); the chase below runs
    # only once a sense has flipped it to aggro. See npc/agro.py.
    agro_nodes = _author_agro(ed, after_extras, _pin(pathable, "execute"),
                              BEL.find_execute_pin(delay), agro,
                              origin.x - 200, origin.y + 3000)

    # --- the straight line ---------------------------------------------------
    # Not a teleport, not AddMovementInput, and not a second Tick: this is the
    # SAME move request the pathfinding branch issues, with pathfinding off, so
    # the path-following component drives the character with the same
    # acceleration and the same stop condition and keeps doing it between loop
    # iterations. AddMovementInput would move the NPC for exactly one frame out
    # of every thirty, because this loop runs twice a second.
    #
    # bProjectDestinationToNavigation must stay FALSE. True is the dead zone,
    # written a different way: it snaps the goal back onto the navmesh island
    # and the NPC walks to the edge and stops.
    direct = _at(_node(ed, FN_MOVE_TO_LOCATION), origin.x + 1000, origin.y + 200)
    _connect(goal_out, _pin(direct, "Dest"))
    _set(direct, "AcceptanceRadius", NPC_ACCEPTANCE_RADIUS_CM)
    _set(direct, "bUsePathfinding", "false")
    _set(direct, "bProjectDestinationToNavigation", "false")
    _set(direct, "bStopOnOverlap", "true")
    _set(direct, "bCanStrafe", "false")
    _connect(BEL.find_else_pin(pathable), BEL.find_execute_pin(direct))

    after_move = (BEL.find_then_pin(move_to), BEL.find_then_pin(direct))

    _connect(BEL.find_else_pin(gate), BEL.find_execute_pin(delay))

    melee = _author_melee(ed, after_move, delay, origin.x + 1400, origin.y,
                          melee_anim=melee_anim)
    if melee is None:
        for tail in after_move:
            _connect(tail, BEL.find_execute_pin(delay))

    ed.add_comment_to_nodes(
        f"Re-issue a move order at the player every {NPC_REPATH_SECONDS} s, "
        f"once the controller has a pawn to move. Pathfinding when both ends "
        f"are on the navmesh -- which is what runs the NPC around trees -- and "
        f"a straight-line move order when either end is not, because the "
        f"navmesh only covers a disc inside the terrain and a player in the "
        f"ring outside it used to be simply unreachable.",
        [move_to, get_pawn, delay, gate, own_pawn, possessed, reach, goal_loc,
         goal_on, here_pawn, here_loc, here_on, both_on, pathable, direct])
    if melee:
        ed.add_comment_to_nodes(
            f"Melee: within {NPC_MELEE_RANGE_CM:.0f} cm and off cooldown, swing "
            f"for {NPC_MELEE_DAMAGE:.0f} damage, then arm the next swing "
            f"{NPC_MELEE_INTERVAL_S} s out. The cooldown is per controller, so "
            f"a pack does not hit in lockstep.",
            melee)

    ed.add_comment_to_nodes(
        f"This creature's own health ({health:.0f}), applied once on the first "
        f"heartbeat after possession, and its voice every "
        f"{NPC_VOICE_MIN_S:.0f}-{NPC_VOICE_MAX_S:.0f} s. Health is set from "
        f"here rather than on the pawn because MaxHealth lives on an INHERITED "
        f"component, and Unreal keeps a child Blueprint's override of one in an "
        f"InheritableComponentHandler that Python cannot reach.",
        extras)

    ed.add_comment_to_nodes(
        f"Patrol until noticed: stroll a {agro.patrol_radius_cm / 100:.0f} m "
        f"circle about the spawn point at {agro.patrol_speed_scale:.0%} of run "
        f"speed; go aggro, for good, when hurt, when the player is seen "
        f"({agro.vision_range_cm / 100:.0f} m, "
        f"{agro.vision_half_angle_deg:.0f} deg either side, line of sight), "
        f"touched ({agro.touch_range_cm:.0f} cm) or heard (the noise's own "
        f"reach x {agro.hearing_scale}).",
        agro_nodes)

    if not BEL.compile_blueprint(bp):
        raise RuntimeError(f"{path} failed to compile")

    # The sound arrays are defaults on the class, not pin literals -- an array
    # cannot be written into a pin. Missing files are dropped rather than
    # raising: /Game/Audio is built from assets/generated/sounds, which a
    # checkout that has not run Scripts/make_creature_sounds.py does not have,
    # and the graph already guards an empty array.
    eas = _asset_sub()
    cdo = unreal.get_default_object(BEL.generated_class(bp))
    for var, wanted in ((VOICES_VAR, voices), (HIT_SOUNDS_VAR, hit_sounds)):
        found = [eas.load_asset(a) for a in wanted if eas.does_asset_exist(a)]
        cdo.set_editor_property(var, found)
        if len(found) != len(wanted):
            _log(f"note: {path} {var}: {len(found)} of {len(wanted)} sounds "
                 f"exist -- run Scripts/make_creature_sounds.py, then "
                 f"build_weapons_and_combat.py, to import the rest")

    # The flinches, same mechanism, but ALL SIX OR NONE: the reaction graph
    # indexes this array by position (three Fronts, then Back, Left, Right), so
    # a partial set is not a shorter list, it is the wrong clip for three of the
    # four directions -- and that failure is silent, where an empty array simply
    # means this creature does not flinch.
    clips = [eas.load_asset(a) for a in reactions if eas.does_asset_exist(a)]
    if len(clips) != len(reactions):
        _log(f"note: {path}: {len(clips)} of {len(reactions)} hit reactions "
             f"exist -- run Scripts/asset_pipeline/build_retarget.py. This "
             f"creature will not flinch.")
        clips = []
    cdo.set_editor_property(REACTIONS_VAR, clips)

    eas.save_loaded_asset(bp)
    _log(f"built {path} ({len(cdo.get_editor_property(REACTIONS_VAR))} hit "
         f"reactions, health {health:.0f}"
         + (f", melee {NPC_MELEE_DAMAGE:.0f} dmg / {NPC_MELEE_INTERVAL_S} s "
            f"inside {NPC_MELEE_RANGE_CM:.0f} cm" if melee else ", no melee")
         + f", {len(cdo.get_editor_property(VOICES_VAR))} voices, patrols "
         f"{agro.patrol_radius_cm / 100:.0f} m, sees "
         f"{agro.vision_range_cm / 100:.0f} m)")
    return bp
