"""uebp.nodes.math -- KismetMathLibrary: arithmetic, comparison, vectors,
rotators, and INF.
"""

FN_ABS = "/Script/Engine.KismetMathLibrary.Abs"
FN_ADD_FF = "/Script/Engine.KismetMathLibrary.Add_DoubleDouble"
FN_ADD_II = "/Script/Engine.KismetMathLibrary.Add_IntInt"
FN_ADD_VV = "/Script/Engine.KismetMathLibrary.Add_VectorVector"
FN_AND = "/Script/Engine.KismetMathLibrary.BooleanAND"
FN_AXIS_ANGLE = "/Script/Engine.KismetMathLibrary.RotatorFromAxisAndAngle"
FN_BOOL_TO_FLOAT = "/Script/Engine.KismetMathLibrary.Conv_BoolToDouble"
FN_BREAK_ROT = "/Script/Engine.KismetMathLibrary.BreakRotator"
FN_BREAK_TRANSFORM = "/Script/Engine.KismetMathLibrary.BreakTransform"
FN_BREAK_V2D = "/Script/Engine.KismetMathLibrary.BreakVector2D"
FN_BREAK_VECTOR = "/Script/Engine.KismetMathLibrary.BreakVector"
FN_CEIL = "/Script/Engine.KismetMathLibrary.FCeil"
FN_CLAMP = "/Script/Engine.KismetMathLibrary.FClamp"
# Integer clamp, not FClamp: the reaction index is an array index, and an array
# shorter than HIT_REACTION_CLIPS (a checkout whose retarget has not run) must
# clip to the last entry rather than read off the end.
FN_CLAMP_II = "/Script/Engine.KismetMathLibrary.Clamp"
FN_CLASS_EQ = "/Script/Engine.KismetMathLibrary.EqualEqual_ClassClass"
FN_CLASS_IS_CHILD = "/Script/Engine.KismetMathLibrary.ClassIsChildOf"
FN_COLOR_LERP = "/Script/Engine.KismetMathLibrary.LinearColorLerp"
FN_COMPOSE_ROT = "/Script/Engine.KismetMathLibrary.ComposeRotators"
FN_CROSS = "/Script/Engine.KismetMathLibrary.Cross_VectorVector"
FN_DEG2RAD = "/Script/Engine.KismetMathLibrary.DegreesToRadians"
FN_DEG_ATAN2 = "/Script/Engine.KismetMathLibrary.DegAtan2"
FN_DEG_COS = "/Script/Engine.KismetMathLibrary.DegCos"
FN_DEG_SIN = "/Script/Engine.KismetMathLibrary.DegSin"
# The reticle's size (weapon_component/accuracy.py): the cloud's angle as a
# fraction of the half-width the field of view spans.
FN_DEG_TAN = "/Script/Engine.KismetMathLibrary.DegTan"
FN_DISTANCE = "/Script/Engine.KismetMathLibrary.Vector_Distance"
FN_DISTANCE_2D = "/Script/Engine.KismetMathLibrary.Vector_Distance2D"
FN_DIV_FF = "/Script/Engine.KismetMathLibrary.Divide_DoubleDouble"
# The hit-direction pick. Dot_VectorVector against the owner's own forward and
# right is what turns "where the round came from" into one of four clips
# without a single angle or a single trigonometric function.
FN_DOT_VV = "/Script/Engine.KismetMathLibrary.Dot_VectorVector"
FN_EQ_CC = "/Script/Engine.KismetMathLibrary.EqualEqual_ClassClass"
FN_EQ_FF = "/Script/Engine.KismetMathLibrary.EqualEqual_DoubleDouble"
FN_EQ_II = "/Script/Engine.KismetMathLibrary.EqualEqual_IntInt"
FN_EQ_NAME = "/Script/Engine.KismetMathLibrary.EqualEqual_NameName"
FN_EQ_OO = "/Script/Engine.KismetMathLibrary.EqualEqual_ObjectObject"
FN_EXP = "/Script/Engine.KismetMathLibrary.Exp"
FN_FMIN = "/Script/Engine.KismetMathLibrary.FMin"
FN_FMOD = "/Script/Engine.KismetMathLibrary.FMod"
FN_FORWARD = "/Script/Engine.KismetMathLibrary.GetForwardVector"
FN_FRACTION = "/Script/Engine.KismetMathLibrary.Fraction"
FN_GE_FF = "/Script/Engine.KismetMathLibrary.GreaterEqual_DoubleDouble"
FN_GE_II = "/Script/Engine.KismetMathLibrary.GreaterEqual_IntInt"
FN_GREATER_FF = "/Script/Engine.KismetMathLibrary.Greater_DoubleDouble"
FN_GREATER_II = "/Script/Engine.KismetMathLibrary.Greater_IntInt"
FN_INTERP_FF = "/Script/Engine.KismetMathLibrary.FInterpTo"
FN_INT_TO_FLOAT = "/Script/Engine.KismetMathLibrary.Conv_IntToDouble"
FN_INV_XFORM_DIR = "/Script/Engine.KismetMathLibrary.InverseTransformDirection"
FN_IN_RANGE = "/Script/Engine.KismetMathLibrary.InRange_FloatFloat"
FN_LERP = "/Script/Engine.KismetMathLibrary.Lerp"
# The step between two swings (npc/strafe.py).
FN_LESS_FF = "/Script/Engine.KismetMathLibrary.Less_DoubleDouble"
FN_LESS_II = "/Script/Engine.KismetMathLibrary.Less_IntInt"
FN_LE_FF = "/Script/Engine.KismetMathLibrary.LessEqual_DoubleDouble"
FN_LE_II = "/Script/Engine.KismetMathLibrary.LessEqual_IntInt"
FN_MAKE_COLOR = "/Script/Engine.KismetMathLibrary.MakeColor"
FN_MAKE_ROT = "/Script/Engine.KismetMathLibrary.MakeRotator"
FN_MAKE_TRANSFORM = "/Script/Engine.KismetMathLibrary.MakeTransform"
FN_MAKE_VECTOR = "/Script/Engine.KismetMathLibrary.MakeVector"
FN_MAP_CLAMPED = "/Script/Engine.KismetMathLibrary.MapRangeClamped"
# The noise record (combat/noise.py): the louder of two reaches, and whether a
# footstep belongs to the player rather than to one of the wanderers who share
# the footstep component.
FN_MAX_FF = "/Script/Engine.KismetMathLibrary.FMax"
FN_MAX_II = "/Script/Engine.KismetMathLibrary.Max"
FN_MIN_II = "/Script/Engine.KismetMathLibrary.Min"
FN_MOD_II = "/Script/Engine.KismetMathLibrary.Percent_IntInt"
FN_MUL_FF = "/Script/Engine.KismetMathLibrary.Multiply_DoubleDouble"
FN_MUL_II = "/Script/Engine.KismetMathLibrary.Multiply_IntInt"
FN_MUL_VF = "/Script/Engine.KismetMathLibrary.Multiply_VectorFloat"
FN_MUL_VV = "/Script/Engine.KismetMathLibrary.Multiply_VectorVector"
FN_NEGATE_V = "/Script/Engine.KismetMathLibrary.NegateVector"
FN_NEQ_BB = "/Script/Engine.KismetMathLibrary.NotEqual_BoolBool"
FN_NEQ_FF = "/Script/Engine.KismetMathLibrary.NotEqual_DoubleDouble"
FN_NEQ_II = "/Script/Engine.KismetMathLibrary.NotEqual_IntInt"
FN_NE_CC = "/Script/Engine.KismetMathLibrary.NotEqual_ClassClass"
FN_NE_NAME = "/Script/Engine.KismetMathLibrary.NotEqual_NameName"
FN_NE_OO = "/Script/Engine.KismetMathLibrary.NotEqual_ObjectObject"
FN_NORMAL = "/Script/Engine.KismetMathLibrary.Normal"
# The control rotation keeps pitch in 0..360; this makes looking down negative.
FN_NORMALIZE_AXIS = "/Script/Engine.KismetMathLibrary.NormalizeAxis"
FN_NORMAL_2D = "/Script/Engine.KismetMathLibrary.Vector_Normal2D"
FN_NOT = "/Script/Engine.KismetMathLibrary.Not_PreBool"
FN_OR = "/Script/Engine.KismetMathLibrary.BooleanOR"
FN_PERCENT_FF = "/Script/Engine.KismetMathLibrary.Percent_FloatFloat"
FN_RANDOM_BOOL = "/Script/Engine.KismetMathLibrary.RandomBool"
FN_RANDOM_FLOAT = "/Script/Engine.KismetMathLibrary.RandomFloatInRange"
FN_RANDOM_UNIT = "/Script/Engine.KismetMathLibrary.RandomFloat"
FN_RAND_CONE = "/Script/Engine.KismetMathLibrary.RandomUnitVectorInConeInRadians"
FN_RAND_INT = "/Script/Engine.KismetMathLibrary.RandomIntegerInRange"
FN_RLERP = "/Script/Engine.KismetMathLibrary.RLerp"
FN_ROTATE_AXIS = "/Script/Engine.KismetMathLibrary.RotateAngleAxis"
FN_ROTATE_VECTOR = "/Script/Engine.KismetMathLibrary.GreaterGreater_VectorRotator"
FN_ROT_FROM_X = "/Script/Engine.KismetMathLibrary.MakeRotFromX"
FN_ROUND = "/Script/Engine.KismetMathLibrary.Round"
FN_SEED_STREAM = "/Script/Engine.KismetMathLibrary.SeedRandomStream"
FN_SELECT_COLOR = "/Script/Engine.KismetMathLibrary.SelectColor"
FN_SELECT_FF = "/Script/Engine.KismetMathLibrary.SelectFloat"
FN_SELECT_II = "/Script/Engine.KismetMathLibrary.SelectInt"
FN_SELECT_OBJ = "/Script/Engine.KismetMathLibrary.SelectObject"
FN_SELECT_STR = "/Script/Engine.KismetMathLibrary.SelectString"
FN_SELECT_VECTOR = "/Script/Engine.KismetMathLibrary.SelectVector"
FN_SET_STREAM_SEED = "/Script/Engine.KismetMathLibrary.SetRandomStreamSeed"
FN_SIN = "/Script/Engine.KismetMathLibrary.Sin"
FN_SQRT = "/Script/Engine.KismetMathLibrary.Sqrt"
# FRandomStream draws. Pure, and they advance the stream they read (its Seed is
# mutable), so each must be pulled by exactly one exec consumer. The seeders
# take the stream by reference and write the variable they are wired to.
FN_STREAM_FLOAT = "/Script/Engine.KismetMathLibrary.RandomFloatFromStream"
FN_STREAM_INT = "/Script/Engine.KismetMathLibrary.RandomIntegerFromStream"
FN_SUB_FF = "/Script/Engine.KismetMathLibrary.Subtract_DoubleDouble"
FN_SUB_II = "/Script/Engine.KismetMathLibrary.Subtract_IntInt"
FN_SUB_VV = "/Script/Engine.KismetMathLibrary.Subtract_VectorVector"
FN_TRANSFORM_LOC = "/Script/Engine.KismetMathLibrary.TransformLocation"
FN_VEC2_NE = "/Script/Engine.KismetMathLibrary.NotEqualExactly_Vector2DVector2D"
FN_VEC_TO_COLOR = "/Script/Engine.KismetMathLibrary.Conv_VectorToLinearColor"
FN_VEC_TO_ROT = "/Script/Engine.KismetMathLibrary.Conv_VectorToRotator"
FN_VLERP = "/Script/Engine.KismetMathLibrary.VLerp"
FN_VSIZE = "/Script/Engine.KismetMathLibrary.VSize"
FN_VSIZE_XY = "/Script/Engine.KismetMathLibrary.VSizeXY"
FN_XOR = "/Script/Engine.KismetMathLibrary.BooleanXOR"

INF = 1000000000.0
